### ISSUE TITLE
Missing `Resource` properties needed for documentation report

### ISSUE THREAD

**Issue by andrii-balitskyi** [seamapi/blueprint#113]
1. `isUndocumented`:
- resource
2. `isDraft`:
- resource
3. `isDeprecated`:
- resource
4. `deprecationMessage`:
- resource

**Comment by andrii-balitskyi** [comment]
Also https://github.com/seamapi/blueprint/issues/111

**Comment by razor-x** [comment]
@andrii-balitskyi Description for route and namespace can be added to the schema, but we can't fill them in here. We need to fill them in via https://github.com/seamapi/docs/pull/329

**Comment by andrii-balitskyi** [comment]
@razor-x got it, I updated the issue to remove those. 

> Description and deprecationMessage for route and namespace can be added to the schema

What schema are you referring to?
