### ISSUE TITLE
Python code samples should support array responses

### ISSUE THREAD

**Issue by andrii-balitskyi** [seamapi/blueprint#44]

**Comment by andrii-balitskyi** [comment]
@razor-x I've noticed the Python code samples don't account for array responses. There's an implementation detail I'd like your input on: when we receive an array response, we pluralize the response key. However, our Python classes use singular names. How do you think we should handle mapping these plural response keys to our singular Seam resource names?

**Comment by razor-x** [comment]
Why does this only apply to python and not the other SDKs? Can you show an example of what you are referring to?

**Comment by andrii-balitskyi** [comment]
@razor-x This issue also affects Ruby, but not JS and PHP since they return JSON representations rather than class instances. For Python, if the `responseKey` is `"devices"`, we'd need to map it to singular `"device"` and return a list of `Device` instances: `[Device(...), Device(...)]`. Our current implementation only supports singular resource responses like `"device": {...}` -> `Device(...)`.
How should we approach mapping these plural response keys to our singular Seam resource names?

**Comment by razor-x** [comment]
Can we use `resourceType`? This was fixed recently here: https://github.com/seamapi/blueprint/pull/48
![image](https://github.com/user-attachments/assets/2f3968c1-888f-42d6-92c1-05a805c25814)

**Comment by andrii-balitskyi** [comment]
Oh nice! Yea, that should work. Thanks!
