### ISSUE TITLE
fix(Code Sample/PHP): update response type to be php

### ISSUE THREAD

**Issue by mikewuu** [seamapi/blueprint#60]
> Not for this PR, but this really should be php

_Originally posted by @razor-x in https://github.com/seamapi/blueprint/pull/58#discussion_r1714659877_

**Comment by razor-x** [comment]
@andrii-balitskyi Was the json response type for PHP intentional? Isn't there a PHP class for each resource?

**Comment by andrii-balitskyi** [comment]
@razor-x Yes, you're right, there's a class for each resource. I was referencing our current docs where we put JSON in the PHP response example. My bad.
I'm not sure how a PHP-style response should look.
Something like this:
![image](https://github.com/user-attachments/assets/5796867a-354e-461c-b1d5-e00cc7e93042)?

**Comment by razor-x** [comment]
@andrii-balitskyi For rendering the response for each language, let's use the primitive literal syntax. I realize the actual return value is a wrapper data class, but it's not possible to format that via a formatter, and it can't be copy-pasted into an interpreter.

So for PHP, this would be

```php
[
    "connected_account_id" => "...",
    "is_managed" => True,
]
```
