### ISSUE TITLE
Break up `Parameter` interface into the different types/formats 

### ISSUE THREAD

**Issue by andrii-balitskyi** [seamapi/blueprint#63]
Really we need to follow what we did for Property and break it up into the difference types/formats.

But that can be the next PR

_Originally posted by @razor-x in https://github.com/seamapi/blueprint/pull/62#discussion_r1727266637_

**Comment by andrii-balitskyi** [comment]
@razor-x should we use interfaces defined for `Property` something like:
```ts
export interface BaseParameter {
  name: string
  isRequired: boolean
  isUndocumented: boolean
  isDeprecated: boolean
  deprecationMessage: string
  description: string
}

export type Parameter =
  | (BaseParameter & StringProperty)
  | (BaseParameter & EnumProperty)
  | (BaseParameter & RecordProperty)
  | (BaseParameter & ListProperty)
  | (BaseParameter & ObjectProperty)
  | (BaseParameter & BooleanProperty)
  | (BaseParameter & DatetimeProperty)
  | (BaseParameter & IdProperty)
```

**Comment by razor-x** [comment]
@andrii-balitskyi Yes (but we can use the interface extension pattern we already have). I expect the properties / parameters will share a similar structure at first, but they will diverge as we build the docs/sdks since params are about input and properties are about output.
