### ISSUE TITLE
Generate /events and event resource

### ISSUE THREAD

**Issue by razor-x** [seamapi/blueprint#74]
We have `blueprint.routes` and `blueprint.resources`. I think we need `blueprint.events because while we have the union types, we still need to pick out specific members of the unions to document on each page.

But first, before we add `blueprint.events`, let's see what happens if we try to generate the blueprint for `/events` and the `event` resource.

**Comment by mikewuu** [comment]
@razor-x any thoughts on adding `blueprint.events`? Is it just an enum?

**Comment by razor-x** [comment]
@mikewuu It would be something like `events: EventResource[]` where each `EventResource` is one of the union elements, basically an element for each thing in this array: https://github.com/seamapi/types/blob/d7b349400cacdf9741b43a501c02665401189881/src/lib/seam/connect/models/events/seam-event.ts#L13-L20

```ts
interface EventResource extends Resource {
  event_type: string
}
```

**Comment by andrii-balitskyi** [comment]
```
interface EventResource extends Resource {
  resourceType: 'event'
  eventType: string
  routePath: string
  targetResourceType: string
}
```
